/*
 *
 */
package org.vaadin.addons.excelexporter;

import java.util.ArrayList;
import java.util.List;

import net.karneim.pojobuilder.GeneratePojoBuilder;

/**
 * The Class ExportExcelConfiguration is used to configure the Excel Worksheet. The filename, extension, generatedBy, and sheet configurations can also be
 * configured.
 *
 * @author Kartik Suba
 */
@GeneratePojoBuilder(
    intoPackage = "*.builder")
public class ExportExcelConfiguration {

    /** The export file name. */
    private String exportFileName;

    /** The dateRequiredInFileName */
    private Boolean dateRequiredInFileName = Boolean.TRUE;

    public Boolean getDateRequiredInFileName() {
        return this.dateRequiredInFileName;
    }

    public void setDateRequiredInFileName(final Boolean dateRequiredInFileName) {
        this.dateRequiredInFileName = dateRequiredInFileName;
    }

    /** The generated by. */
    String generatedBy;

    /** The export type. */
    ExportType exportType;

    /** The export extension. */
    String exportExtension;

    /** The sheet configs. */
    List<ExportExcelSheetConfiguration> sheetConfigs = new ArrayList<>();

    /**
     * Gets the export file name.
     *
     * @return the export file name
     */
    public String getExportFileName() {
        return this.exportFileName;
    }

    /**
     * Gets the generated by.
     *
     * @return the generated by
     */
    public String getGeneratedBy() {
        return this.generatedBy;
    }

    /**
     * Gets the export type.
     *
     * @return the export type
     */
    public ExportType getExportType() {
        return this.exportType;
    }

    /**
     * Gets the export extension.
     *
     * @return the export extension
     */
    public String getExportExtension() {
        return this.exportExtension;
    }

    /**
     * Sets the export file name.
     *
     * @param exportFileName the new export file name
     */
    public void setExportFileName(final String exportFileName) {
        this.exportFileName = exportFileName;
    }

    /**
     * Sets the generated by.
     *
     * @param generatedBy the new generated by
     */
    public void setGeneratedBy(final String generatedBy) {
        this.generatedBy = generatedBy;
    }

    /**
     * Sets the export type.
     *
     * @param exportType the new export type
     */
    public void setExportType(final ExportType exportType) {
        this.exportType = exportType;
    }

    /**
     * Sets the export extension.
     *
     * @param exportExtension the new export extension
     */
    public void setExportExtension(final String exportExtension) {
        this.exportExtension = exportExtension;
    }

    /**
     * Gets the sheet configs.
     *
     * @return the sheet configs
     */
    public List<ExportExcelSheetConfiguration> getSheetConfigs() {
        return this.sheetConfigs;
    }

    /**
     * Sets the sheet configs.
     *
     * @param sheetConfigs the new sheet configs
     */
    public void setSheetConfigs(final List<ExportExcelSheetConfiguration> sheetConfigs) {
        this.sheetConfigs = sheetConfigs;
    }
}
