package org.vaadin.addons;

import java.awt.Color;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.math.BigDecimal;
import java.text.DateFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Collection;
import java.util.Date;
import java.util.HashMap;
import java.util.Hashtable;
import java.util.Iterator;
import java.util.List;
import java.util.Locale;
import java.util.Map;

import org.apache.poi.ss.usermodel.BorderStyle;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.Font;
import org.apache.poi.ss.usermodel.IndexedColors;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.util.CellRangeAddress;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFCellStyle;
import org.apache.poi.xssf.usermodel.XSSFColor;
import org.apache.poi.xssf.usermodel.XSSFDataFormat;
import org.apache.poi.xssf.usermodel.XSSFFont;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.apache.poi.xssf.usermodel.extensions.XSSFCellBorder.BorderSide;

import com.vaadin.data.fieldgroup.FieldGroup;
import com.vaadin.data.util.IndexedContainer;
import com.vaadin.ui.Grid;
import com.vaadin.ui.Table;
import com.vaadin.ui.TreeTable;
import com.vaadin.ui.UI;

/**
 * @author Kartik Suba
 *
 */
public class ExportToExcelUtility<BEANTYPE> extends ExportUtility {

    /**
     * 
     */

    Boolean isPreProcessingPerformed = Boolean.FALSE;

    XSSFWorkbook workbook;
    String resultantExportFileName = null;
    File tempReportFile = null;
    final String DEFAULT_SHEET_NAME = "Sheet";
    String DEFAULT_FILE_NAME = "Export_";
    UI sourceUI = null;

    ExportExcelConfiguration exportExcelConfiguration;
    Class typeClass = null;

    Hashtable<String, Method> methodMap = new Hashtable<String, Method>();

    private ExportType resultantExportType = null;

    public ExportType getResultantExportType() {
        return this.resultantExportType;
    }

    public void setResultantExportType(final ExportType resultantExportType) {
        this.resultantExportType = resultantExportType;
    }

    private String resultantSelectedExtension;

    /************************************** Constructors *********************************************************/
    public ExportToExcelUtility() {
    }

    public ExportToExcelUtility(final UI ui, final ExportExcelConfiguration exportExcelConfiguration, final Class typeClass) {

        this.exportExcelConfiguration = exportExcelConfiguration;
        this.sourceUI = ui;
        this.typeClass = typeClass;
        performPreprocessing(exportExcelConfiguration);
    }

    /************************************** Constructors *********************************************************/

    /************************************** Pre-processing and Book-keeping Information *************************/
    protected void performPreprocessing(final ExportExcelConfiguration exportExcelConfiguration) {

        getDefaultFileName();
        this.isPreProcessingPerformed = Boolean.TRUE;
        this.exportExcelConfiguration = exportExcelConfiguration;

        int sheetIndex = 0;
        for (ExportExcelSheetConfiguration sheetConfig : exportExcelConfiguration.getSheetConfigs()) {
            sheetConfig.setResultantSheetName((sheetConfig.getSheetName() != null && !sheetConfig.getSheetName()
                                                                                                 .isEmpty()) ? sheetConfig.getSheetName()
                    : this.DEFAULT_SHEET_NAME + sheetIndex + 1);
            sheetConfig.setResultantReportTitleRowContent(sheetConfig.getReportTitleRowContent() != null ? sheetConfig.getReportTitleRowContent()
                    : "Report Name: " + sheetConfig.getReportTitle());
            sheetConfig.setResultantLoggerInfoRowContent(sheetConfig.getLoggerInfoRowContent() != null ? sheetConfig.getLoggerInfoRowContent()
                    : "Report generated by: " + exportExcelConfiguration.getGeneratedBy() + "  on " + formatDate(new Date(), sheetConfig));
            sheetConfig.setResultantColumnForTitleRegion((sheetConfig.getColumnForTitleRegion() != null && sheetConfig.getColumnForTitleRegion()[0] != null) ? sheetConfig.getColumnForTitleRegion()
                    : new Integer[] { 0, 3 });
            sheetConfig.setResultantColumnForGeneratedByRegion((sheetConfig.getColumnForGeneratedByRegion() != null && sheetConfig.getColumnForGeneratedByRegion()[0] != null) ? sheetConfig.getColumnForGeneratedByRegion()
                    : new Integer[] { 0, 3 });
            sheetConfig.setResultantHeaderCaptionStartCol(sheetConfig.getHeaderCaptionStartCol());
            sheetConfig.setResultantHeaderValueStartCol(sheetConfig.getHeaderValueStartCol());
            sheetIndex++;
        }
        this.resultantExportType = exportExcelConfiguration.getExportType();

        // one's. Asynchronous Call.
        Thread thread = new Thread(new Runnable() {

            @Override
            public void run() {

                Date d1 = new Date();
                getAllMethods(ExportToExcelUtility.this.typeClass, ExportToExcelUtility.this.methodMap);
                Date d2 = new Date();
            }
        });
        thread.start();
    }

    public void getDefaultFileName() {
        Calendar calendar = Calendar.getInstance();
        this.DEFAULT_FILE_NAME = this.DEFAULT_FILE_NAME + calendar.get(Calendar.DATE) + "_" + (calendar.get(Calendar.MONTH) + 1) + "_"
                + calendar.get(Calendar.YEAR) + "__" + calendar.get(Calendar.HOUR) + "_" + calendar.get(Calendar.MINUTE) + "_" + calendar.get(Calendar.SECOND);
    }

    protected void performInitialization() {

        if (this.resultantExportType.equals(ExportType.XLS)) {
            this.resultantSelectedExtension = "xls";
        }
        else {
            this.resultantSelectedExtension = "xlsx";
        }
        Calendar calendar = Calendar.getInstance();
        this.resultantExportFileName = ((this.exportExcelConfiguration.getExportFileName() != null && !this.exportExcelConfiguration.getExportFileName()
                                                                                                                                    .isEmpty()) ? this.exportExcelConfiguration.getExportFileName()
                + "_" + calendar.get(Calendar.YEAR) + "_" + (calendar.get(Calendar.MONTH) + 1) + "_" + calendar.get(Calendar.DATE)
                : this.DEFAULT_FILE_NAME)
                + "." + this.resultantSelectedExtension;

        this.workbook = new XSSFWorkbook();

        // Initializing Default Styles
        for (ExportExcelSheetConfiguration sheetConfig : this.exportExcelConfiguration.getSheetConfigs()) {
            sheetConfig.setSheet(this.workbook.createSheet(sheetConfig.getResultantSheetName()));
            sheetConfig.setrReportTitleStyle((sheetConfig.getReportTitleStyle() != null) ? sheetConfig.getReportTitleStyle()
                    : getDefaultReportTitleStyle(this.workbook));
            sheetConfig.setrGeneratedByStyle((sheetConfig.getGeneratedByStyle() != null) ? sheetConfig.getGeneratedByStyle()
                    : getDefaultReportTitleStyle(this.workbook));
            sheetConfig.setrHeaderCaptionStyle((sheetConfig.getHeaderCaptionStyle() != null) ? sheetConfig.getHeaderCaptionStyle()
                    : getDefaultHeaderCaptionStyle(this.workbook));
            sheetConfig.setrHeaderValueStyle((sheetConfig.getHeaderValueStyle() != null) ? sheetConfig.getHeaderValueStyle()
                    : getDefaultHeaderValueStyle(this.workbook));
            sheetConfig.setrAdditionalHeaderCaptionStyle((sheetConfig.getAdditionalHeaderCaptionStyle() != null) ? sheetConfig.getAdditionalHeaderCaptionStyle()
                    : getDefaultAddHeaderCaptionStyle(this.workbook));
            sheetConfig.setrAdditionalHeaderValueStyle((sheetConfig.getAdditionalHeaderValueStyle() != null) ? sheetConfig.getAdditionalHeaderValueStyle()
                    : getDefaultAddHeaderValueStyle(this.workbook));

            for (ExportExcelComponentConfiguration componentConfig : sheetConfig.getComponentConfigs()) {
                componentConfig.setrTableHeaderStyle((componentConfig.getTableHeaderStyle() != null) ? componentConfig.getTableHeaderStyle()
                        : getDefaultTableHeaderStyle(this.workbook));
                componentConfig.setrTableContentStyle((componentConfig.getTableContentStyle() != null) ? componentConfig.getTableContentStyle()
                        : getDefaultTableContentStyle(this.workbook));
            }
        }
    }

    protected Integer addReportTitleAtFirst(final XSSFWorkbook myWorkBook, final ExportExcelSheetConfiguration sheetConfiguration) {

        if (sheetConfiguration.getReportTitle() != null) {
            // Creating Report Name Row
            Row myHeaderRow1 = sheetConfiguration.getSheet()
                                                 .createRow(sheetConfiguration.getDefaultSheetRowNum());
            Cell myHeaderCell1 = myHeaderRow1.createCell(0);
            myHeaderCell1.setCellValue(sheetConfiguration.getResultantReportTitleRowContent());
            myHeaderCell1.setCellStyle(sheetConfiguration.getrReportTitleStyle());
            sheetConfiguration.getSheet()
                              .addMergedRegion(new CellRangeAddress(sheetConfiguration.getDefaultSheetRowNum(), sheetConfiguration.getDefaultSheetRowNum(),
                                                       sheetConfiguration.getResultantColumnForTitleRegion()[0],
                                                       sheetConfiguration.getResultantColumnForTitleRegion()[1]));

            // Adding AutoBreaks
            sheetConfiguration.getSheet()
                              .setAutobreaks(true);

            sheetConfiguration.setDefaultSheetRowNum(sheetConfiguration.getDefaultSheetRowNum() + 1);
            // Adding an empty row after title
        }

        return sheetConfiguration.getDefaultSheetRowNum();
    }

    protected Integer addGeneratedByAtFirst(final XSSFWorkbook myWorkBook, final ExportExcelSheetConfiguration sheetConfiguration) {

        if (sheetConfiguration.getResultantLoggerInfoRowContent() != null && !sheetConfiguration.getResultantLoggerInfoRowContent()
                                                                                                .isEmpty()) {
            // Creating Generated By Row
            sheetConfiguration.setDefaultSheetRowNum(sheetConfiguration.getDefaultSheetRowNum() + 1);
            // Adding an empty row before generated by
            Row myHeaderRow2 = sheetConfiguration.getSheet()
                                                 .createRow(sheetConfiguration.getDefaultSheetRowNum());
            Cell myHeaderCell2 = myHeaderRow2.createCell(0);
            myHeaderCell2.setCellValue(sheetConfiguration.getResultantLoggerInfoRowContent());
            myHeaderCell2.setCellStyle(sheetConfiguration.getrGeneratedByStyle());
            sheetConfiguration.getSheet()
                              .addMergedRegion(new CellRangeAddress(sheetConfiguration.getDefaultSheetRowNum(), sheetConfiguration.getDefaultSheetRowNum(),
                                                       sheetConfiguration.getResultantColumnForGeneratedByRegion()[0],
                                                       sheetConfiguration.getResultantColumnForGeneratedByRegion()[1]));

            // Adding AutoBreaks
            sheetConfiguration.getSheet()
                              .setAutobreaks(true);

            sheetConfiguration.setDefaultSheetRowNum(sheetConfiguration.getDefaultSheetRowNum() + 1);
            // Adding an empty row after generated by
        }

        return sheetConfiguration.getDefaultSheetRowNum();
    }

    /************************************** Pre-processing and Book-keeping Information *************************/

    /************************************* Adding Vaadin Grid To Sheet *******************************************/
    protected Integer addVaadinGridToExcelSheet(final Grid grid, final XSSFWorkbook myWorkBook, final ExportExcelSheetConfiguration sheetConfiguration,
            final ExportExcelComponentConfiguration componentConfiguration) {
        Integer stIdx = sheetConfiguration.getDefaultSheetRowNum();

        if (this.workbook.getSheet(sheetConfiguration.getResultantSheetName()) != null) {
            sheetConfiguration.setSheet(this.workbook.getSheet(sheetConfiguration.getResultantSheetName()));
        }
        else {
            sheetConfiguration.setSheet(this.workbook.createSheet(sheetConfiguration.getResultantSheetName()));
        }

        if (sheetConfiguration.getIsHeaderSectionRequired()) {
            stIdx = createGridHeaderSection(grid, myWorkBook, sheetConfiguration, componentConfiguration);
        }

        stIdx = createGridContent(grid, myWorkBook, sheetConfiguration, componentConfiguration);

        return stIdx;
    }

    protected Integer createGridHeaderSection(final Grid sourceTable, final XSSFWorkbook myWorkBook, final ExportExcelSheetConfiguration sheetConfiguration,
            final ExportExcelComponentConfiguration componentConfiguration) {

        return createGenericHeaderSection(null, null, myWorkBook, sheetConfiguration, componentConfiguration);

    }

    protected Integer createGridContent(final Grid grid, final XSSFWorkbook myWorkBook, final ExportExcelSheetConfiguration sheetConfiguration,
            final ExportExcelComponentConfiguration componentConfiguration) {
        return createGenericContent(grid.getContainerDataSource()
                                        .getItemIds(), myWorkBook, sheetConfiguration, componentConfiguration);
    }

    /************************************* Adding Vaadin Grid To Sheet *******************************************/

    /************************************* Adding Vaadin Table To Sheet *******************************************/
    protected Integer addTableToExcelSheet(final Table grid, final XSSFWorkbook myWorkBook, final ExportExcelSheetConfiguration sheetConfiguration,
            final ExportExcelComponentConfiguration componentConfiguration) {
        Integer stIdx = sheetConfiguration.getDefaultSheetRowNum();

        if (this.workbook.getSheet(sheetConfiguration.getResultantSheetName()) != null) {
            sheetConfiguration.setSheet(this.workbook.getSheet(sheetConfiguration.getResultantSheetName()));
        }
        else {
            sheetConfiguration.setSheet(this.workbook.createSheet(sheetConfiguration.getResultantSheetName()));
        }

        if (sheetConfiguration.getIsHeaderSectionRequired()) {
            stIdx = createGridHeaderSection(grid, myWorkBook, sheetConfiguration, componentConfiguration);
        }

        stIdx = createGridContent(grid, myWorkBook, sheetConfiguration, componentConfiguration);

        return stIdx;
    }

    protected Integer createGridHeaderSection(final Table sourceTable, final XSSFWorkbook myWorkBook, final ExportExcelSheetConfiguration sheetConfiguration,
            final ExportExcelComponentConfiguration componentConfiguration) {

        return createGenericHeaderSection(null, null, myWorkBook, sheetConfiguration, componentConfiguration);

    }

    protected Integer createGridContent(final Table grid, final XSSFWorkbook myWorkBook, final ExportExcelSheetConfiguration sheetConfiguration,
            final ExportExcelComponentConfiguration componentConfiguration) {
        return createGenericContent(grid.getContainerDataSource()
                                        .getItemIds(), myWorkBook, sheetConfiguration, componentConfiguration);
    }

    /************************************* Adding Vaadin Table To Sheet *******************************************/

    /************************************ Adding Tree Table To Sheet ***********************************************/
    protected Integer addTreeTableToExcelSheet(final TreeTable treeTable, final XSSFWorkbook myWorkBook,
            final ExportExcelSheetConfiguration sheetConfiguration, final ExportExcelComponentConfiguration componentConfiguration) {
        Integer stIdx = sheetConfiguration.getDefaultSheetRowNum();

        if (this.workbook.getSheet(sheetConfiguration.getResultantSheetName()) != null) {
            sheetConfiguration.setSheet(this.workbook.getSheet(sheetConfiguration.getResultantSheetName()));
        }
        else {
            sheetConfiguration.setSheet(this.workbook.createSheet(sheetConfiguration.getResultantSheetName()));
        }

        if (sheetConfiguration.getIsHeaderSectionRequired()) {
            stIdx = createTreeTableHeaderSection(treeTable, myWorkBook, sheetConfiguration, componentConfiguration);
        }

        stIdx = createTreeTableContent(treeTable, myWorkBook, sheetConfiguration, componentConfiguration);

        return stIdx;
    }

    protected Integer createTreeTableHeaderSection(final TreeTable treeTable, final XSSFWorkbook myWorkBook,
            final ExportExcelSheetConfiguration sheetConfiguration, final ExportExcelComponentConfiguration componentConfiguration) {

        return createGenericHeaderSection(null, null, myWorkBook, sheetConfiguration, componentConfiguration);

    }

    protected Integer createTreeTableContent(final TreeTable treeTable, final XSSFWorkbook myWorkBook, final ExportExcelSheetConfiguration sheetConfiguration,
            final ExportExcelComponentConfiguration componentConfiguration) {

        final Collection<?> itemIds = treeTable.getContainerDataSource()
                                               .getItemIds();

        if (sheetConfiguration.getIsHeaderSectionAdded()) {
            sheetConfiguration.setDefaultSheetRowNum(sheetConfiguration.getDefaultSheetRowNum() + 1);
        }

        sheetConfiguration.getSheet()
                          .setRowBreak(sheetConfiguration.getDefaultSheetRowNum());

        Integer firstRow = new Integer(sheetConfiguration.getDefaultSheetRowNum());
        Row myRow = sheetConfiguration.getSheet()
                                      .createRow(sheetConfiguration.getDefaultSheetRowNum());

        if (componentConfiguration.getColRowFreeze() != null) {
            sheetConfiguration.getSheet()
                              .createFreezePane(componentConfiguration.getColRowFreeze(), sheetConfiguration.getDefaultSheetRowNum() + 1);
        }

        // Adding Column Headers
        for (int columns = 0; columns < componentConfiguration.getVisibleProperties().length; columns++) {
            Cell myCell = myRow.createCell(columns, XSSFCell.CELL_TYPE_STRING);
            myCell.setCellValue(componentConfiguration.getColumnHeaderKeys()[columns]);
            sheetConfiguration.getSheet()
                              .autoSizeColumn(columns, false);
            myCell.setCellStyle(componentConfiguration.getrTableHeaderStyle());
        }

        sheetConfiguration.setDefaultSheetRowNum(sheetConfiguration.getDefaultSheetRowNum() + 1);

        Date d3 = new Date();
        for (final Object itemId : itemIds) {

            addGenericDataRow(componentConfiguration.getVisibleProperties(), myWorkBook, sheetConfiguration, componentConfiguration, itemId,
                              sheetConfiguration.getDefaultSheetRowNum(), treeTable.getContainerDataSource()
                                                                                   .hasChildren(itemId));
            sheetConfiguration.setDefaultSheetRowNum(sheetConfiguration.getDefaultSheetRowNum() + 1);
        }
        Date d4 = new Date();

        // Disabling auto columns for each column
        for (int columns = 0; columns < componentConfiguration.getVisibleProperties().length; columns++) {
            sheetConfiguration.getSheet()
                              .autoSizeColumn(columns, false);
        }

        // Adding auto filter in the Excel Header
        sheetConfiguration.getSheet()
                          .setAutoFilter(new CellRangeAddress(firstRow, sheetConfiguration.getDefaultSheetRowNum(), 0,
                                                 componentConfiguration.getVisibleProperties().length - 1));

        return sheetConfiguration.getDefaultSheetRowNum();
    }

    /************************************ Adding Tree Table To Sheet ***********************************************/

    /************************************* Generic Code to add Content and Header Section *******************************************/

    protected Integer createGenericHeaderSection(final FieldGroup headerFilterGroup, final String[] visiblePropsInHeader, final XSSFWorkbook myWorkBook,
            final ExportExcelSheetConfiguration sheetConfiguration, final ExportExcelComponentConfiguration componentConfiguration) {
        if (headerFilterGroup != null && visiblePropsInHeader != null) {

            sheetConfiguration.setIsHeaderSectionAdded(true);
            int rowCounter = 0;
            Row row = null;

            for (String property : visiblePropsInHeader) {
                if (headerFilterGroup.getField(property) != null) {
                    if (visiblePropsInHeader.length == 1) {
                        row = sheetConfiguration.getSheet()
                                                .createRow(sheetConfiguration.getDefaultSheetRowNum());
                        sheetConfiguration.setDefaultSheetRowNum(sheetConfiguration.getDefaultSheetRowNum() + 1);
                    }
                    else if (rowCounter % (sheetConfiguration.getNoOfColumnsInHeader()) != 0) {
                        sheetConfiguration.setResultantHeaderCaptionStartCol(sheetConfiguration.getResultantHeaderCaptionStartCol() + 2);
                        sheetConfiguration.setResultantHeaderValueStartCol(sheetConfiguration.getResultantHeaderValueStartCol() + 2);
                    }
                    else {
                        sheetConfiguration.setDefaultSheetRowNum(sheetConfiguration.getDefaultSheetRowNum() + 1);
                        sheetConfiguration.setResultantHeaderCaptionStartCol(0);
                        sheetConfiguration.setResultantHeaderValueStartCol(1);
                        row = sheetConfiguration.getSheet()
                                                .createRow(sheetConfiguration.getDefaultSheetRowNum());
                    }

                    Cell captionCell = row.createCell(sheetConfiguration.getResultantHeaderCaptionStartCol());
                    captionCell.setCellValue(headerFilterGroup.getField(property)
                                                              .getCaption());
                    captionCell.setCellStyle(sheetConfiguration.getrHeaderCaptionStyle());

                    Cell valueCell = row.createCell(sheetConfiguration.getResultantHeaderValueStartCol());
                    valueCell.setCellStyle(sheetConfiguration.getrHeaderValueStyle());
                    if (headerFilterGroup.getField(property)
                                         .getValue() != null) {
                        valueCell.setCellValue(headerFilterGroup.getField(property)
                                                                .getValue()
                                                                .toString());
                    }
                    else {
                        valueCell.setCellValue("");
                    }

                    rowCounter++;
                }
            }
        }

        int additionalInfoCounter = 0;
        if (sheetConfiguration.getAdditionalHeaderInfo() != null && !sheetConfiguration.getAdditionalHeaderInfo()
                                                                                       .isEmpty()) {

            if (sheetConfiguration.getIsHeaderSectionAdded()) {
                sheetConfiguration.setDefaultSheetRowNum(sheetConfiguration.getDefaultSheetRowNum() + 1); // Adding
                                                                                                          // an
                                                                                                          // empty
                                                                                                          // row
                                                                                                          // after
                                                                                                          // Header
                // Section
            }
            else {

                sheetConfiguration.setIsHeaderSectionAdded(Boolean.TRUE);
            }

            Iterator<Map.Entry<String, String>> it = sheetConfiguration.getAdditionalHeaderInfo()
                                                                       .entrySet()
                                                                       .iterator();
            Row row = null;

            while (it.hasNext()) {
                Map.Entry<String, String> me = it.next();
                if (additionalInfoCounter % (sheetConfiguration.getNoOfColumnsInAddHeader()) != 0) {
                    sheetConfiguration.setResultantHeaderCaptionStartCol(sheetConfiguration.getResultantHeaderCaptionStartCol()
                            + sheetConfiguration.getNoOfColumnsToMergeInAddHeaderValue() + 1);
                    sheetConfiguration.setResultantHeaderValueStartCol(sheetConfiguration.getResultantHeaderValueStartCol()
                            + sheetConfiguration.getNoOfColumnsToMergeInAddHeaderValue() + 1);
                }
                else {
                    sheetConfiguration.setDefaultSheetRowNum(sheetConfiguration.getDefaultSheetRowNum() + 1);
                    sheetConfiguration.setResultantHeaderCaptionStartCol(0);
                    sheetConfiguration.setResultantHeaderValueStartCol(1);
                    row = sheetConfiguration.getSheet()
                                            .createRow(sheetConfiguration.getDefaultSheetRowNum());
                }

                Cell captionCell = row.createCell(sheetConfiguration.getResultantHeaderCaptionStartCol());
                captionCell.setCellValue(me.getKey());
                captionCell.setCellStyle(sheetConfiguration.getrAdditionalHeaderCaptionStyle());

                Cell valueCell = row.createCell(sheetConfiguration.getResultantHeaderValueStartCol());
                valueCell.setCellStyle(sheetConfiguration.getrAdditionalHeaderValueStyle());

                CellRangeAddress valueMerged = new CellRangeAddress(sheetConfiguration.getDefaultSheetRowNum(), sheetConfiguration.getDefaultSheetRowNum(),
                        sheetConfiguration.getResultantHeaderValueStartCol(), sheetConfiguration.getResultantHeaderValueStartCol()
                                + (sheetConfiguration.getNoOfColumnsToMergeInAddHeaderValue() - 1));
                sheetConfiguration.getSheet()
                                  .addMergedRegion(valueMerged);

                if (me.getValue() != null) {
                    valueCell.setCellValue(me.getValue());
                }
                else {
                    valueCell.setCellValue("");
                }

                additionalInfoCounter++;
            }
        }

        if (sheetConfiguration.getIsHeaderSectionAdded()) {
            sheetConfiguration.setDefaultSheetRowNum(sheetConfiguration.getDefaultSheetRowNum() + 1); // Adding
                                                                                                      // an
                                                                                                      // empty
                                                                                                      // row
                                                                                                      // after
                                                                                                      // Additional
            // Header Section
        }

        return sheetConfiguration.getDefaultSheetRowNum();
    }

    protected Integer createGenericContent(final Collection<?> itemIds, final XSSFWorkbook myWorkBook, final ExportExcelSheetConfiguration sheetConfiguration,
            final ExportExcelComponentConfiguration componentConfiguration) {

        if (sheetConfiguration.getIsHeaderSectionAdded()) {
            sheetConfiguration.setDefaultSheetRowNum(sheetConfiguration.getDefaultSheetRowNum() + 1);
        }

        sheetConfiguration.getSheet()
                          .setRowBreak(sheetConfiguration.getDefaultSheetRowNum());

        Integer firstRow = new Integer(sheetConfiguration.getDefaultSheetRowNum());
        Row myRow = sheetConfiguration.getSheet()
                                      .createRow(sheetConfiguration.getDefaultSheetRowNum());

        if (componentConfiguration.getColRowFreeze() != null) {
            sheetConfiguration.getSheet()
                              .createFreezePane(componentConfiguration.getColRowFreeze(), sheetConfiguration.getDefaultSheetRowNum());
        }

        Date d1 = new Date();
        // Adding Column Headers
        for (int columns = 0; columns < componentConfiguration.getVisibleProperties().length; columns++) {
            Cell myCell = myRow.createCell(columns, XSSFCell.CELL_TYPE_STRING);
            myCell.setCellValue(componentConfiguration.getColumnHeaderKeys()[columns]);
            sheetConfiguration.getSheet()
                              .autoSizeColumn(columns, false);
            myCell.setCellStyle(componentConfiguration.getrTableHeaderStyle());
        }
        Date d2 = new Date();

        sheetConfiguration.setDefaultSheetRowNum(sheetConfiguration.getDefaultSheetRowNum() + 1);
        for (final Object itemId : itemIds) {
            addGenericDataRow(componentConfiguration.getVisibleProperties(), myWorkBook, sheetConfiguration, componentConfiguration, itemId,
                              sheetConfiguration.getDefaultSheetRowNum(), Boolean.FALSE);
            sheetConfiguration.setDefaultSheetRowNum(sheetConfiguration.getDefaultSheetRowNum() + 1);
        }

        Date d5 = new Date();

        // Disabling auto columns for each column
        for (int columns = 0; columns < componentConfiguration.getVisibleProperties().length; columns++) {
            sheetConfiguration.getSheet()
                              .autoSizeColumn(columns, false);
        }

        // Adding auto filter in the Excel Header
        sheetConfiguration.getSheet()
                          .setAutoFilter(new CellRangeAddress(firstRow, sheetConfiguration.getDefaultSheetRowNum(), 0,
                                                 componentConfiguration.getVisibleProperties().length - 1));

        return sheetConfiguration.getDefaultSheetRowNum();
    }

    protected void addGenericDataRow(final Object[] visibleColumns, final XSSFWorkbook myWorkBook, final ExportExcelSheetConfiguration sheetConfiguration,
            final ExportExcelComponentConfiguration componentConfiguration, final Object itemId, final Integer localRow, final Boolean isParent) {
        Row myRow = sheetConfiguration.getSheet()
                                      .createRow(localRow);
        try {

            for (int columns = 0; columns < visibleColumns.length; columns++) {

                Object obj = null;
                if (componentConfiguration.getTable() != null && componentConfiguration.getTable()
                                                                                       .getContainerDataSource() instanceof IndexedContainer) {
                    obj = componentConfiguration.getTable()
                                                .getItem(itemId)
                                                .getItemProperty(visibleColumns[columns])
                                                .getValue();
                }
                else if (componentConfiguration.getGrid() != null && componentConfiguration.getGrid()
                                                                                           .getContainerDataSource() instanceof IndexedContainer) {
                    obj = componentConfiguration.getGrid()
                                                .getContainerDataSource()
                                                .getContainerProperty(itemId, visibleColumns[columns])
                                                .getValue();
                }
                else if (this.methodMap.containsKey(String.valueOf(visibleColumns[columns]))) {
                    obj = this.methodMap.get(String.valueOf(visibleColumns[columns]))
                                        .invoke(itemId);
                }
                Cell myCell = myRow.createCell(columns, XSSFCell.CELL_TYPE_STRING);

                if ((obj != null)) {
                    if (componentConfiguration.getDateFormattingProperties() != null
                            && componentConfiguration.getDateFormattingProperties()
                                                     .contains(String.valueOf(visibleColumns[columns]))) {
                        myCell.setCellValue(formatDate((Date) obj, sheetConfiguration));
                    }
                    else if (componentConfiguration.getIntegerFormattingProperties() != null
                            && componentConfiguration.getIntegerFormattingProperties()
                                                     .contains(String.valueOf(visibleColumns[columns]))) {
                        myCell.setCellValue(localizedFormat(obj != null && !String.valueOf(obj)
                                                                                  .isEmpty() ? String.valueOf(obj) : null, Boolean.TRUE));
                    }
                    else if (componentConfiguration.getFloatFormattingProperties() != null
                            && componentConfiguration.getFloatFormattingProperties()
                                                     .contains(String.valueOf(visibleColumns[columns]))) {
                        if (obj instanceof Double) {
                            myCell.setCellValue(formatFloat((Double) obj));
                        }
                        else if (obj instanceof BigDecimal) {
                            {
                                myCell.setCellValue(formatFloat(((BigDecimal) obj).doubleValue()));
                            }
                        }
                    }
                    else {
                        myCell.setCellValue(obj.toString());
                    }
                }
                else {
                    myCell.setCellValue("");
                }

                if (isParent) {
                    myCell.setCellStyle(getDefaultTableContentParentStyle(myWorkBook));
                }
                if (localRow % 2 == 0) {
                    myCell.setCellStyle(isParent ? getDefaultTableContentParentStyle(myWorkBook) : componentConfiguration.getrTableContentStyle());
                }

            }
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void getAllMethods(Class type, final Hashtable<String, Method> map) {

        while (type != Object.class) {
            for (final Field field : type.getDeclaredFields()) {

                if (!field.getName()
                          .equals("serialVersionUID")) {
                    field.setAccessible(true);

                    String name = field.getName()
                                       .substring(0, 1)
                                       .toUpperCase()
                                       .concat(field.getName()
                                                    .substring(1));
                    Method method;
                    try {
                        method = type.getMethod("get" + name);
                        if (method == null) {
                            method = type.getMethod("is" + name);
                        }
                        if (method != null) {
                            map.put(field.getName(), method);
                        }
                    }
                    catch (NoSuchMethodException | SecurityException e) {
                        e.printStackTrace();
                    }

                }
            }
            type = type.getSuperclass();
        }

    }

    public List<Field> getAllFields(List<Field> fields, final Class<?> type, final Map<String, Field> map) {
        fields.addAll(Arrays.asList(type.getDeclaredFields()));

        if (type.getSuperclass() != null) {
            fields = getAllFields(fields, type.getSuperclass(), map);
        }

        for (Field field : fields) {
            map.put(field.getName(), field);
        }
        return fields;
    }

    /************************************* Generic Code to add Content and Header Section *******************************************/

    /************************************* Using above methods to add data in to Excel *******************************************/

    protected Boolean addConfiguredComponentToExcel() {

        if (this.isPreProcessingPerformed) {
            performInitialization();

            for (ExportExcelSheetConfiguration sheetConfig : this.exportExcelConfiguration.getSheetConfigs()) {
                if (sheetConfig.getIsDefaultSheetTitleRequired()) {
                    sheetConfig.setDefaultSheetRowNum(addReportTitleAtFirst(this.workbook, sheetConfig));
                }

                if (sheetConfig.getIsDefaultGeneratedByRequired()) {
                    sheetConfig.setDefaultSheetRowNum(addGeneratedByAtFirst(this.workbook, sheetConfig));
                }

                for (ExportExcelComponentConfiguration componentConfig : sheetConfig.getComponentConfigs()) {
                    if (componentConfig.getGrid() != null) {
                        sheetConfig.setDefaultSheetRowNum(addVaadinGridToExcelSheet(componentConfig.getGrid(), this.workbook, sheetConfig, componentConfig));
                    }

                    if (componentConfig.getTreeTable() != null) {
                        sheetConfig.setDefaultSheetRowNum(addTreeTableToExcelSheet(componentConfig.getTreeTable(), this.workbook, sheetConfig, componentConfig));
                    }

                    if (componentConfig.getTable() != null) {
                        sheetConfig.setDefaultSheetRowNum(addTableToExcelSheet(componentConfig.getTable(), this.workbook, sheetConfig, componentConfig));
                    }
                    sheetConfig.setDefaultSheetRowNum(sheetConfig.getDefaultSheetRowNum() + 1);
                }
            }
        }

        return this.isPreProcessingPerformed;
    }

    @Override
    protected File generateReportFile() {

        Boolean proceed = addConfiguredComponentToExcel();
        File tempFile = null;
        if (proceed) {

            FileOutputStream fileOut = null;
            try {
                tempFile = File.createTempFile("tmp", "." + this.resultantSelectedExtension);
                fileOut = new FileOutputStream(tempFile);
                this.workbook.write(fileOut);
                if (null == this.mimeType) {
                    setMimeType(EXCEL_MIME_TYPE);
                }
            }
            catch (final IOException e) {
                LOGGER.warning("Converting to XLS failed with IOException " + e);
                return null;
            }
            finally {
                if (tempFile != null) {
                    tempFile.deleteOnExit();
                }
                try {
                    if (fileOut != null) {
                        fileOut.close();
                    }
                }
                catch (final IOException e) {
                }
            }

            this.tempReportFile = tempFile;
        }
        return tempFile;
    }

    /**
     * Export the workbook to the end-user.
     * 
     * Code obtained from: http://vaadin.com/forum/-/message_boards/view_message/159583
     * 
     * @return true, if successful
     */
    @Override
    protected boolean sendConverted() {
        final boolean success = super.sendConvertedFileToUser(this.sourceUI, this.tempReportFile, this.resultantExportFileName);
        return success;
    }

    /************************************* Using above methods to add data in to Excel *******************************************/

    /************************************* Getters and Setters *******************************************/
    public UI getSourceUI() {
        return this.sourceUI;
    }

    public void setSourceUI(final UI sourceUI) {
        this.sourceUI = sourceUI;
    }

    public XSSFWorkbook getWorkbook() {
        return this.workbook;
    }

    protected Map<String, XSSFCellStyle> createStyles(final XSSFWorkbook wb) {
        Map<String, XSSFCellStyle> styles = new HashMap<String, XSSFCellStyle>();
        XSSFDataFormat fmt = wb.createDataFormat();

        XSSFCellStyle style1 = wb.createCellStyle();
        style1.setAlignment(XSSFCellStyle.ALIGN_RIGHT);
        style1.setDataFormat(fmt.getFormat("0.0%"));
        style1.setWrapText(false);
        styles.put("percent", style1);

        XSSFCellStyle style2 = wb.createCellStyle();
        style2.setAlignment(XSSFCellStyle.ALIGN_CENTER);
        style2.setDataFormat(fmt.getFormat("0.0X"));
        style2.setWrapText(false);
        styles.put("coeff", style2);

        XSSFCellStyle style3 = wb.createCellStyle();
        style3.setAlignment(XSSFCellStyle.ALIGN_RIGHT);
        style3.setDataFormat(fmt.getFormat("$#,##0.00"));
        style3.setWrapText(false);
        styles.put("currency", style3);

        XSSFCellStyle style4 = wb.createCellStyle();
        style4.setAlignment(XSSFCellStyle.ALIGN_RIGHT);
        style4.setDataFormat(fmt.getFormat("mmm dd"));
        style4.setWrapText(false);
        styles.put("date", style4);

        XSSFCellStyle style5 = wb.createCellStyle();
        XSSFFont headerFont = wb.createFont();
        headerFont.setBold(true);
        style5.setFillForegroundColor(IndexedColors.GREY_25_PERCENT.getIndex());
        style5.setFillPattern(XSSFCellStyle.SOLID_FOREGROUND);
        style5.setFont(headerFont);
        style5.setWrapText(false);
        styles.put("header", style5);

        XSSFCellStyle style6 = wb.createCellStyle();
        XSSFFont font = wb.createFont();
        font.setBoldweight(Font.BOLDWEIGHT_BOLD);
        style6.setFont(font);
        style6.setWrapText(false);
        styles.put("reportFormat", style6);

        return styles;
    }

    /************************************* Getters and Setters *******************************************/

    /************************************* Styles and Designing of Excel Content *******************************************/
    protected XSSFCellStyle getDefaultReportTitleStyle(final XSSFWorkbook myWorkBook) {
        XSSFCellStyle defaultReportTitleStyle = myWorkBook.createCellStyle();

        XSSFFont boldFont = myWorkBook.createFont();
        boldFont.setBoldweight(Font.BOLDWEIGHT_BOLD);
        boldFont.setFontHeightInPoints((short) 14);

        defaultReportTitleStyle.setFont(boldFont);

        return defaultReportTitleStyle;
    }

    protected XSSFCellStyle getDefaultGeneratedByStyle(final XSSFWorkbook myWorkBook) {
        XSSFCellStyle defaultGeneratedByStyle = myWorkBook.createCellStyle();
        XSSFFont boldFont = myWorkBook.createFont();
        boldFont.setBoldweight(Font.BOLDWEIGHT_BOLD);
        boldFont.setFontHeightInPoints((short) 10);

        defaultGeneratedByStyle.setFont(boldFont);

        return defaultGeneratedByStyle;
    }

    protected XSSFCellStyle getDefaultHeaderCaptionStyle(final XSSFWorkbook myWorkBook) {
        XSSFCellStyle headerCellStyle = myWorkBook.createCellStyle();
        headerCellStyle = myWorkBook.createCellStyle();
        headerCellStyle.setFillForegroundColor(new XSSFColor(new Color(50, 86, 110)));
        headerCellStyle.setFillPattern(XSSFCellStyle.SOLID_FOREGROUND);
        headerCellStyle = setBorders(headerCellStyle, Boolean.TRUE, Boolean.TRUE, Boolean.TRUE, Boolean.TRUE);

        XSSFFont boldFont = myWorkBook.createFont();
        boldFont.setBoldweight(Font.BOLDWEIGHT_BOLD);
        boldFont.setColor(IndexedColors.WHITE.getIndex());

        headerCellStyle.setFont(boldFont);

        return headerCellStyle;
    }

    protected XSSFCellStyle getDefaultHeaderValueStyle(final XSSFWorkbook myWorkBook) {
        XSSFCellStyle headerCellStyle = myWorkBook.createCellStyle();
        headerCellStyle = myWorkBook.createCellStyle();
        headerCellStyle.setFillForegroundColor(new XSSFColor(new Color(209, 220, 227)));
        headerCellStyle.setFillPattern(XSSFCellStyle.SOLID_FOREGROUND);
        headerCellStyle.setAlignment(CellStyle.ALIGN_CENTER);
        headerCellStyle = setBorders(headerCellStyle, Boolean.TRUE, Boolean.TRUE, Boolean.TRUE, Boolean.TRUE);

        XSSFFont boldFont = myWorkBook.createFont();

        headerCellStyle.setFont(boldFont);

        return headerCellStyle;
    }

    protected XSSFCellStyle getDefaultAddHeaderCaptionStyle(final XSSFWorkbook myWorkBook) {
        XSSFCellStyle headerCellStyle = myWorkBook.createCellStyle();
        headerCellStyle = myWorkBook.createCellStyle();
        headerCellStyle.setFillForegroundColor(new XSSFColor(new Color(50, 86, 110)));
        headerCellStyle.setFillPattern(XSSFCellStyle.SOLID_FOREGROUND);
        headerCellStyle = setBorders(headerCellStyle, Boolean.TRUE, Boolean.TRUE, Boolean.TRUE, Boolean.TRUE);

        XSSFFont boldFont = myWorkBook.createFont();
        boldFont.setBoldweight(Font.BOLDWEIGHT_BOLD);
        boldFont.setColor(IndexedColors.WHITE.getIndex());

        headerCellStyle.setFont(boldFont);

        return headerCellStyle;
    }

    protected XSSFCellStyle getDefaultAddHeaderValueStyle(final XSSFWorkbook myWorkBook) {
        XSSFCellStyle headerCellStyle = myWorkBook.createCellStyle();
        headerCellStyle = myWorkBook.createCellStyle();
        headerCellStyle.setFillForegroundColor(new XSSFColor(new Color(209, 220, 227)));
        headerCellStyle.setFillPattern(XSSFCellStyle.SOLID_FOREGROUND);
        headerCellStyle.setAlignment(CellStyle.ALIGN_CENTER);
        headerCellStyle.setWrapText(true);

        XSSFFont boldFont = myWorkBook.createFont();

        headerCellStyle.setFont(boldFont);

        return headerCellStyle;
    }

    protected XSSFCellStyle getDefaultTableHeaderStyle(final XSSFWorkbook myWorkBook) {
        XSSFCellStyle headerCellStyle = myWorkBook.createCellStyle();
        headerCellStyle = myWorkBook.createCellStyle();
        headerCellStyle.setFillForegroundColor(new XSSFColor(new Color(50, 86, 110)));
        headerCellStyle.setFillPattern(XSSFCellStyle.SOLID_FOREGROUND);
        headerCellStyle.setAlignment(CellStyle.ALIGN_LEFT);

        XSSFFont boldFont = myWorkBook.createFont();
        boldFont.setColor(IndexedColors.WHITE.getIndex());
        boldFont.setBoldweight(Font.BOLDWEIGHT_BOLD);

        headerCellStyle.setFont(boldFont);

        return headerCellStyle;
    }

    protected XSSFCellStyle getDefaultTableContentStyle(final XSSFWorkbook myWorkBook) {
        XSSFCellStyle cellStyle = myWorkBook.createCellStyle();
        cellStyle = myWorkBook.createCellStyle();
        cellStyle.setFillForegroundColor(new XSSFColor(new Color(228, 234, 238)));
        cellStyle.setFillPattern(XSSFCellStyle.SOLID_FOREGROUND);

        return cellStyle;
    }

    protected XSSFCellStyle getDefaultTableContentParentStyle(final XSSFWorkbook myWorkBook) {
        XSSFCellStyle cellStyle = myWorkBook.createCellStyle();
        cellStyle = myWorkBook.createCellStyle();
        cellStyle.setFillForegroundColor(new XSSFColor(new Color(189, 203, 211)));
        cellStyle.setFillPattern(XSSFCellStyle.SOLID_FOREGROUND);
        XSSFFont boldFont = myWorkBook.createFont();
        boldFont.setBoldweight(Font.BOLDWEIGHT_BOLD);

        cellStyle.setFont(boldFont);
        return cellStyle;
    }

    protected XSSFCellStyle setBorders(final XSSFCellStyle headerCellStyle, final Boolean left, final Boolean right, final Boolean top, final Boolean bottom) {
        if (bottom) {
            headerCellStyle.setBorderBottom(BorderStyle.THIN);
            headerCellStyle.setBorderColor(BorderSide.BOTTOM, new XSSFColor(Color.BLACK));
        }

        if (top) {
            headerCellStyle.setBorderTop(BorderStyle.THIN);
            headerCellStyle.setBorderColor(BorderSide.TOP, new XSSFColor(Color.BLACK));
        }

        if (left) {
            headerCellStyle.setBorderLeft(BorderStyle.THIN);
            headerCellStyle.setBorderColor(BorderSide.LEFT, new XSSFColor(Color.BLACK));
        }

        if (right) {
            headerCellStyle.setBorderRight(BorderStyle.THIN);
            headerCellStyle.setBorderColor(BorderSide.RIGHT, new XSSFColor(Color.BLACK));
        }

        return headerCellStyle;
    }

    /************************************* Styles and Designing of Excel Content *******************************************/

    private String formatDate(final Date val, final ExportExcelSheetConfiguration sheetConfiguration) {
        if (val == null) {
            return null;
        }
        DateFormat df = new SimpleDateFormat(sheetConfiguration.getDateFormat(), this.sourceUI.getLocale());
        return df.format(val);
    }

    public String localizedFormat(final String value, final Boolean isIntOrBigD) {
        Locale loc = this.sourceUI.getLocale();
        if (isIntOrBigD) {
            Integer modifiedValue = unLocalizedFormatForInt(value);

            NumberFormat nf = NumberFormat.getNumberInstance(loc);
            nf.setParseIntegerOnly(true);
            return nf.format(modifiedValue);
        }
        else {
            BigDecimal modifiedValue = unLocalizedFormatForBigDecimal(value);
            NumberFormat nf = NumberFormat.getNumberInstance(loc);
            nf.setMinimumFractionDigits(2);
            nf.setMaximumFractionDigits(2);
            return nf.format(modifiedValue);
        }

    }

    public String formatFloat(final Double value) {
        Locale loc = this.sourceUI.getLocale();
        NumberFormat nf = NumberFormat.getNumberInstance(loc);
        nf.setMinimumFractionDigits(2);
        nf.setMaximumFractionDigits(2);
        return nf.format(value);
    }

    public Integer unLocalizedFormatForInt(final String value) {
        Locale loc = this.sourceUI.getLocale();
        Integer modifiedValue = 0;

        if (value != null && !value.contains(".") && !value.contains(",")) {
            modifiedValue = Integer.valueOf(value);
        }
        else {
            if (value != null && loc.getLanguage()
                                    .equals("en")) {
                modifiedValue = Integer.valueOf(value.replaceAll(",", ""));
            }
            else if (value != null && loc.getLanguage()
                                         .equals("de")) {
                modifiedValue = Integer.valueOf(value.replaceAll("\\.", ""));
            }
        }
        return modifiedValue;
    }

    public BigDecimal unLocalizedFormatForBigDecimal(final String value) {
        Locale loc = UI.getCurrent()
                       .getLocale();
        BigDecimal modifiedValue = new BigDecimal(Double.valueOf("0"));

        if (value != null && !value.contains(".") && !value.contains(",")) {

            modifiedValue = BigDecimal.valueOf(Double.valueOf(value));
        }
        else {
            if (value != null && loc.getLanguage()
                                    .equals("en")) {

                modifiedValue = BigDecimal.valueOf(Double.valueOf(value.replaceAll(",", "")));
            }
            else if (value != null && loc.getLanguage()
                                         .equals("de")) {

                String temp = value;
                if (value.contains(".")) {
                    temp = value.replaceAll("\\.", "");

                }
                if (temp.contains(",")) {
                    temp = temp.replaceAll(",", "\\.");

                }
                modifiedValue = BigDecimal.valueOf(Double.valueOf(temp));
            }
        }
        return modifiedValue;
    }
}
